version: '3'
services:
  peacemakr-services:
    image: 716293438869.dkr.ecr.us-east-2.amazonaws.com/peacemakr-services:testing-stable
    ports:
      - "8080:80"
    depends_on:
      - redis
  keyderiver-cloud:
    image: 716293438869.dkr.ecr.us-east-2.amazonaws.com/key-derivation-service:testing-stable
    environment:
        - PEACEMAKR_KEYDERIVER_PEACEMAKR_HOST=peacemakr-services
    depends_on:
      - peacemakr-services
    links:
      - peacemakr-services
  redis:
    image: "redis:alpine"
  integration-d-anconia-copper:
    image: 716293438869.dkr.ecr.us-east-2.amazonaws.com/integration-tests:testing-stable
    environment:
      - PEACEMAKR_TEST_INTEGRATIONTEST_ADMINEMAIL="bob@danconiacopper.com"
      - PEACEMAKR_TEST_INTEGRATIONTEST_BUILDCOMPANY=true
      - PEACEMAKR_TEST_INTEGRATIONTEST_BUILTCOMPANYNAME="D'Anconia Copper"
      - PEACEMAKR_TEST_INTEGRATIONTEST_NUMCLIENTS=2
      - PEACEMAKR_TEST_INTEGRATIONTEST_NUMUSEDOMAINS=2
      - PEACEMAKR_TEST_INTEGRATIONTEST_NUMKEYSPERUSEDOMAIN=2
      - PEACEMAKR_TEST_INTEGRATIONTEST_NUMOFCRYPTOTRIPS=2
    depends_on:
      - peacemakr-services
      - keyderiver-cloud
    links:
      - peacemakr-services
  integration-test-api:
    image: 716293438869.dkr.ecr.us-east-2.amazonaws.com/integration-tests:testing-stable
    environment:
      - PEACEMAKR_TEST_INTEGRATIONTEST_ADMINEMAIL="bob@testcompany.com"
      - PEACEMAKR_TEST_INTEGRATIONTEST_BUILDCOMPANY=false
      - PEACEMAKR_TEST_INTEGRATIONTEST_NUMCLIENTS=2
      - PEACEMAKR_TEST_INTEGRATIONTEST_NUMUSEDOMAINS=2
      - PEACEMAKR_TEST_INTEGRATIONTEST_NUMKEYSPERUSEDOMAIN=2
      - PEACEMAKR_TEST_INTEGRATIONTEST_NUMOFCRYPTOTRIPS=2
    depends_on:
      - peacemakr-services
      - keyderiver-cloud
    links:
      - peacemakr-services


