version: 2
jobs:
  build:
    machine: true
    java:
      version: openjdk12
    steps:
      - checkout # check out source code to working directory
      - run: $(aws ecr get-login --no-include-email --region us-east-2)
      - run: docker-compose pull || true
      - run: docker-compose down || true
      - run: docker-compose up -d
      - run: ./build.sh
      - run: docker-compose down || true
